#!/usr/bin/env python3
# Generated by edabuilder from your Go API. Do not edit any files under pysrc, as they will be removed/overwritten.

from . import constants


class Time:
    def __init__(
        self,
    ):
        pass

    def to_input(self):
        _rval = {}
        return _rval

    @staticmethod
    def from_input(obj) -> "Time | None":
        if not obj:
            return None
        return Time()
