#!/usr/bin/env python3
# Generated by edabuilder from your Go API. Do not edit any files under pysrc, as they will be removed/overwritten.

from . import constants


class FieldsV1:
    def __init__(
        self,
    ):
        pass

    def to_input(self):
        _rval = {}
        return _rval

    @staticmethod
    def from_input(obj) -> "FieldsV1 | None":
        if not obj:
            return None
        return FieldsV1()


class ShardInfo:
    def __init__(
        self,
        selector: str,
    ):
        self.selector = selector

    def to_input(self):
        _rval = {}
        _rval[constants.Y_SELECTOR] = self.selector
        return _rval

    @staticmethod
    def from_input(obj) -> "ShardInfo | None":
        if not obj:
            return None
        _selector = obj.get(constants.Y_SELECTOR)
        return ShardInfo(
            selector=_selector,
        )


class ListMeta:
    def __init__(
        self,
        self_link: str | None = None,
        resource_version: str | None = None,
        continue_: str | None = None,
        remaining_item_count: int | None = None,
        shard_info: ShardInfo | None = None,
    ):
        self.self_link = self_link
        self.resource_version = resource_version
        self.continue_ = continue_
        self.remaining_item_count = remaining_item_count
        self.shard_info = shard_info

    def to_input(self):
        _rval = {}
        if self.self_link is not None:
            _rval[constants.Y_SELFLINK] = self.self_link
        if self.resource_version is not None:
            _rval[constants.Y_RESOURCEVERSION] = self.resource_version
        if self.continue_ is not None:
            _rval[constants.Y_CONTINUE] = self.continue_
        if self.remaining_item_count is not None:
            _rval[constants.Y_REMAININGITEMCOUNT] = self.remaining_item_count
        if self.shard_info is not None:
            _rval[constants.Y_SHARDINFO] = self.shard_info.to_input()
        return _rval

    @staticmethod
    def from_input(obj) -> "ListMeta | None":
        if not obj:
            return None
        _self_link = obj.get(constants.Y_SELFLINK)
        _resource_version = obj.get(constants.Y_RESOURCEVERSION)
        _continue_ = obj.get(constants.Y_CONTINUE)
        _remaining_item_count = obj.get(constants.Y_REMAININGITEMCOUNT)
        _shard_info = ShardInfo.from_input(obj.get(constants.Y_SHARDINFO))
        return ListMeta(
            self_link=_self_link,
            resource_version=_resource_version,
            continue_=_continue_,
            remaining_item_count=_remaining_item_count,
            shard_info=_shard_info,
        )


class Time:
    def __init__(
        self,
    ):
        pass

    def to_input(self):
        _rval = {}
        return _rval

    @staticmethod
    def from_input(obj) -> "Time | None":
        if not obj:
            return None
        return Time()


class ManagedFieldsEntry:
    def __init__(
        self,
        manager: str | None = None,
        operation: str | None = None,
        api_version: str | None = None,
        time: Time | None = None,
        fields_type: str | None = None,
        fields_v1: FieldsV1 | None = None,
        subresource: str | None = None,
    ):
        self.manager = manager
        self.operation = operation
        self.api_version = api_version
        self.time = time
        self.fields_type = fields_type
        self.fields_v1 = fields_v1
        self.subresource = subresource

    def to_input(self):
        _rval = {}
        if self.manager is not None:
            _rval[constants.Y_MANAGER] = self.manager
        if self.operation is not None:
            _rval[constants.Y_OPERATION] = self.operation
        if self.api_version is not None:
            _rval[constants.Y_APIVERSION] = self.api_version
        if self.time is not None:
            _rval[constants.Y_TIME] = self.time.to_input()
        if self.fields_type is not None:
            _rval[constants.Y_FIELDSTYPE] = self.fields_type
        if self.fields_v1 is not None:
            _rval[constants.Y_FIELDSV1] = self.fields_v1.to_input()
        if self.subresource is not None:
            _rval[constants.Y_SUBRESOURCE] = self.subresource
        return _rval

    @staticmethod
    def from_input(obj) -> "ManagedFieldsEntry | None":
        if not obj:
            return None
        _manager = obj.get(constants.Y_MANAGER)
        _operation = obj.get(constants.Y_OPERATION)
        _api_version = obj.get(constants.Y_APIVERSION)
        _time = Time.from_input(obj.get(constants.Y_TIME))
        _fields_type = obj.get(constants.Y_FIELDSTYPE)
        _fields_v1 = FieldsV1.from_input(obj.get(constants.Y_FIELDSV1))
        _subresource = obj.get(constants.Y_SUBRESOURCE)
        return ManagedFieldsEntry(
            manager=_manager,
            operation=_operation,
            api_version=_api_version,
            time=_time,
            fields_type=_fields_type,
            fields_v1=_fields_v1,
            subresource=_subresource,
        )


class OwnerReference:
    def __init__(
        self,
        api_version: str,
        kind: str,
        name: str,
        uid: str,
        controller: bool | None = None,
        block_owner_deletion: bool | None = None,
    ):
        self.api_version = api_version
        self.kind = kind
        self.name = name
        self.uid = uid
        self.controller = controller
        self.block_owner_deletion = block_owner_deletion

    def to_input(self):
        _rval = {}
        _rval[constants.Y_APIVERSION] = self.api_version
        _rval[constants.Y_KIND] = self.kind
        _rval[constants.Y_NAME] = self.name
        _rval[constants.Y_UID] = self.uid
        if self.controller is not None:
            _rval[constants.Y_CONTROLLER] = self.controller
        if self.block_owner_deletion is not None:
            _rval[constants.Y_BLOCKOWNERDELETION] = self.block_owner_deletion
        return _rval

    @staticmethod
    def from_input(obj) -> "OwnerReference | None":
        if not obj:
            return None
        _api_version = obj.get(constants.Y_APIVERSION)
        _kind = obj.get(constants.Y_KIND)
        _name = obj.get(constants.Y_NAME)
        _uid = obj.get(constants.Y_UID)
        _controller = obj.get(constants.Y_CONTROLLER)
        _block_owner_deletion = obj.get(constants.Y_BLOCKOWNERDELETION)
        return OwnerReference(
            api_version=_api_version,
            kind=_kind,
            name=_name,
            uid=_uid,
            controller=_controller,
            block_owner_deletion=_block_owner_deletion,
        )


class ObjectMeta:
    def __init__(
        self,
        name: str | None = None,
        generate_name: str | None = None,
        namespace: str | None = None,
        self_link: str | None = None,
        uid: str | None = None,
        resource_version: str | None = None,
        generation: int | None = None,
        creation_timestamp: Time | None = None,
        deletion_timestamp: Time | None = None,
        deletion_grace_period_seconds: int | None = None,
        labels: dict[str, str] | None = None,
        annotations: dict[str, str] | None = None,
        owner_references: list[OwnerReference] | None = None,
        finalizers: list[str] | None = None,
        managed_fields: list[ManagedFieldsEntry] | None = None,
    ):
        self.name = name
        self.generate_name = generate_name
        self.namespace = namespace
        self.self_link = self_link
        self.uid = uid
        self.resource_version = resource_version
        self.generation = generation
        self.creation_timestamp = creation_timestamp
        self.deletion_timestamp = deletion_timestamp
        self.deletion_grace_period_seconds = deletion_grace_period_seconds
        self.labels = labels
        self.annotations = annotations
        self.owner_references = owner_references
        self.finalizers = finalizers
        self.managed_fields = managed_fields

    def to_input(self):
        _rval = {}
        if self.name is not None:
            _rval[constants.Y_NAME] = self.name
        if self.generate_name is not None:
            _rval[constants.Y_GENERATENAME] = self.generate_name
        if self.namespace is not None:
            _rval[constants.Y_NAMESPACE] = self.namespace
        if self.self_link is not None:
            _rval[constants.Y_SELFLINK] = self.self_link
        if self.uid is not None:
            _rval[constants.Y_UID] = self.uid
        if self.resource_version is not None:
            _rval[constants.Y_RESOURCEVERSION] = self.resource_version
        if self.generation is not None:
            _rval[constants.Y_GENERATION] = self.generation
        if self.creation_timestamp is not None:
            _rval[constants.Y_CREATIONTIMESTAMP] = self.creation_timestamp.to_input()
        if self.deletion_timestamp is not None:
            _rval[constants.Y_DELETIONTIMESTAMP] = self.deletion_timestamp.to_input()
        if self.deletion_grace_period_seconds is not None:
            _rval[constants.Y_DELETIONGRACEPERIODSECONDS] = self.deletion_grace_period_seconds
        if self.labels is not None:
            _rval[constants.Y_LABELS] = self.labels
        if self.annotations is not None:
            _rval[constants.Y_ANNOTATIONS] = self.annotations
        if self.owner_references is not None:
            _rval[constants.Y_OWNERREFERENCES] = [x.to_input() for x in self.owner_references]
        if self.finalizers is not None:
            _rval[constants.Y_FINALIZERS] = self.finalizers
        if self.managed_fields is not None:
            _rval[constants.Y_MANAGEDFIELDS] = [x.to_input() for x in self.managed_fields]
        return _rval

    @staticmethod
    def from_input(obj) -> "ObjectMeta | None":
        if not obj:
            return None
        _name = obj.get(constants.Y_NAME)
        _generate_name = obj.get(constants.Y_GENERATENAME)
        _namespace = obj.get(constants.Y_NAMESPACE)
        _self_link = obj.get(constants.Y_SELFLINK)
        _uid = obj.get(constants.Y_UID)
        _resource_version = obj.get(constants.Y_RESOURCEVERSION)
        _generation = obj.get(constants.Y_GENERATION)
        _creation_timestamp = Time.from_input(obj.get(constants.Y_CREATIONTIMESTAMP))
        _deletion_timestamp = Time.from_input(obj.get(constants.Y_DELETIONTIMESTAMP))
        _deletion_grace_period_seconds = obj.get(constants.Y_DELETIONGRACEPERIODSECONDS)
        _labels = obj.get(constants.Y_LABELS)
        _annotations = obj.get(constants.Y_ANNOTATIONS)
        _owner_references = []
        if obj.get(constants.Y_OWNERREFERENCES) is not None:
            for _e in obj.get(constants.Y_OWNERREFERENCES):
                _owner_references.append(OwnerReference.from_input(_e))
        _finalizers = obj.get(constants.Y_FINALIZERS)
        _managed_fields = []
        if obj.get(constants.Y_MANAGEDFIELDS) is not None:
            for _e in obj.get(constants.Y_MANAGEDFIELDS):
                _managed_fields.append(ManagedFieldsEntry.from_input(_e))
        return ObjectMeta(
            name=_name,
            generate_name=_generate_name,
            namespace=_namespace,
            self_link=_self_link,
            uid=_uid,
            resource_version=_resource_version,
            generation=_generation,
            creation_timestamp=_creation_timestamp,
            deletion_timestamp=_deletion_timestamp,
            deletion_grace_period_seconds=_deletion_grace_period_seconds,
            labels=_labels,
            annotations=_annotations,
            owner_references=_owner_references,
            finalizers=_finalizers,
            managed_fields=_managed_fields,
        )

    @staticmethod
    def from_name(_name: str):
        return ObjectMeta(name=_name)


class TypeMeta:
    def __init__(
        self,
        kind: str | None = None,
        api_version: str | None = None,
    ):
        self.kind = kind
        self.api_version = api_version

    def to_input(self):
        _rval = {}
        if self.kind is not None:
            _rval[constants.Y_KIND] = self.kind
        if self.api_version is not None:
            _rval[constants.Y_APIVERSION] = self.api_version
        return _rval

    @staticmethod
    def from_input(obj) -> "TypeMeta | None":
        if not obj:
            return None
        _kind = obj.get(constants.Y_KIND)
        _api_version = obj.get(constants.Y_APIVERSION)
        return TypeMeta(
            kind=_kind,
            api_version=_api_version,
        )
