#!/usr/bin/env python3
# Generated by edabuilder from your Go API. Do not edit any files under pysrc, as they will be removed/overwritten.

import eda_common as eda

from . import constants
from . import ext_k8s_io_apimachinery_pkg_apis_meta_v1

USERAUDITCONFIG_SCHEMA = eda.Schema(group="useraudit.eda.edacommunity.com", version="v1alpha1", kind="UserAuditConfig")


class LogFileInfo:
    def __init__(
        self,
        name: str,
        size_bytes: int,
    ):
        self.name = name
        self.size_bytes = size_bytes

    def to_input(self):
        _rval = {}
        _rval[constants.Y_NAME] = self.name
        _rval[constants.Y_SIZEBYTES] = self.size_bytes
        return _rval

    @staticmethod
    def from_input(obj) -> "LogFileInfo | None":
        if not obj:
            return None
        _name = obj.get(constants.Y_NAME)
        _size_bytes = obj.get(constants.Y_SIZEBYTES)
        return LogFileInfo(
            name=_name,
            size_bytes=_size_bytes,
        )


class SubsystemHealth:
    def __init__(
        self,
        eda_api: str | None = None,
        keycloak_events: str | None = None,
    ):
        self.eda_api = eda_api
        self.keycloak_events = keycloak_events

    def to_input(self):
        _rval = {}
        if self.eda_api is not None:
            _rval[constants.Y_EDAAPI] = self.eda_api
        if self.keycloak_events is not None:
            _rval[constants.Y_KEYCLOAKEVENTS] = self.keycloak_events
        return _rval

    @staticmethod
    def from_input(obj) -> "SubsystemHealth | None":
        if not obj:
            return None
        _eda_api = obj.get(constants.Y_EDAAPI)
        _keycloak_events = obj.get(constants.Y_KEYCLOAKEVENTS)
        return SubsystemHealth(
            eda_api=_eda_api,
            keycloak_events=_keycloak_events,
        )


class UserAuditConfigSpec:
    def __init__(
        self,
        poll_interval_seconds: int | None = 300,
        retention_months: int | None = 0,
    ):
        self.poll_interval_seconds = poll_interval_seconds
        self.retention_months = retention_months

    def to_input(self):
        _rval = {}
        if self.poll_interval_seconds is not None:
            _rval[constants.Y_POLLINTERVALSECONDS] = self.poll_interval_seconds
        if self.retention_months is not None:
            _rval[constants.Y_RETENTIONMONTHS] = self.retention_months
        return _rval

    @staticmethod
    def from_input(obj) -> "UserAuditConfigSpec | None":
        if not obj:
            return None
        _poll_interval_seconds = obj.get(constants.Y_POLLINTERVALSECONDS, 300)
        _retention_months = obj.get(constants.Y_RETENTIONMONTHS, 0)
        return UserAuditConfigSpec(
            poll_interval_seconds=_poll_interval_seconds,
            retention_months=_retention_months,
        )


class UserAuditConfigStatus:
    def __init__(
        self,
        health: str | None = None,
        message: str | None = None,
        last_poll_time: str | None = None,
        last_transaction_id: int | None = None,
        last_user_event_ms: int | None = None,
        transactions_processed: int | None = None,
        kc_events_processed: int | None = None,
        log_files: list[LogFileInfo] | None = None,
        subsystems: SubsystemHealth | None = None,
        version: str | None = None,
    ):
        self.health = health
        self.message = message
        self.last_poll_time = last_poll_time
        self.last_transaction_id = last_transaction_id
        self.last_user_event_ms = last_user_event_ms
        self.transactions_processed = transactions_processed
        self.kc_events_processed = kc_events_processed
        self.log_files = log_files
        self.subsystems = subsystems
        self.version = version

    def to_input(self):
        _rval = {}
        if self.health is not None:
            _rval[constants.Y_HEALTH] = self.health
        if self.message is not None:
            _rval[constants.Y_MESSAGE] = self.message
        if self.last_poll_time is not None:
            _rval[constants.Y_LASTPOLLTIME] = self.last_poll_time
        if self.last_transaction_id is not None:
            _rval[constants.Y_LASTTRANSACTIONID] = self.last_transaction_id
        if self.last_user_event_ms is not None:
            _rval[constants.Y_LASTUSEREVENTMS] = self.last_user_event_ms
        if self.transactions_processed is not None:
            _rval[constants.Y_TRANSACTIONSPROCESSED] = self.transactions_processed
        if self.kc_events_processed is not None:
            _rval[constants.Y_KCEVENTSPROCESSED] = self.kc_events_processed
        if self.log_files is not None:
            _rval[constants.Y_LOGFILES] = [x.to_input() for x in self.log_files]
        if self.subsystems is not None:
            _rval[constants.Y_SUBSYSTEMS] = self.subsystems.to_input()
        if self.version is not None:
            _rval[constants.Y_VERSION] = self.version
        return _rval

    @staticmethod
    def from_input(obj) -> "UserAuditConfigStatus | None":
        if not obj:
            return None
        _health = obj.get(constants.Y_HEALTH)
        _message = obj.get(constants.Y_MESSAGE)
        _last_poll_time = obj.get(constants.Y_LASTPOLLTIME)
        _last_transaction_id = obj.get(constants.Y_LASTTRANSACTIONID)
        _last_user_event_ms = obj.get(constants.Y_LASTUSEREVENTMS)
        _transactions_processed = obj.get(constants.Y_TRANSACTIONSPROCESSED)
        _kc_events_processed = obj.get(constants.Y_KCEVENTSPROCESSED)
        _log_files = []
        if obj.get(constants.Y_LOGFILES) is not None:
            for _e in obj.get(constants.Y_LOGFILES):
                _log_files.append(LogFileInfo.from_input(_e))
        _subsystems = SubsystemHealth.from_input(obj.get(constants.Y_SUBSYSTEMS))
        _version = obj.get(constants.Y_VERSION)
        return UserAuditConfigStatus(
            health=_health,
            message=_message,
            last_poll_time=_last_poll_time,
            last_transaction_id=_last_transaction_id,
            last_user_event_ms=_last_user_event_ms,
            transactions_processed=_transactions_processed,
            kc_events_processed=_kc_events_processed,
            log_files=_log_files,
            subsystems=_subsystems,
            version=_version,
        )


class UserAuditConfig:
    def __init__(
        self,
        kind: str | None = None,
        api_version: str | None = None,
        metadata: ext_k8s_io_apimachinery_pkg_apis_meta_v1.ObjectMeta | None = None,
        spec: UserAuditConfigSpec | None = None,
        status: UserAuditConfigStatus | None = None,
    ):
        self.kind = kind
        self.api_version = api_version
        self.metadata = metadata
        self.spec = spec
        self.status = status

    def to_input(self):
        _rval = {}
        if self.kind is not None:
            _rval[constants.Y_KIND] = self.kind
        if self.api_version is not None:
            _rval[constants.Y_APIVERSION] = self.api_version
        if self.metadata is not None:
            _rval[constants.Y_METADATA] = self.metadata.to_input()
        if self.spec is not None:
            _rval[constants.Y_SPEC] = self.spec.to_input()
        if self.status is not None:
            _rval[constants.Y_STATUS] = self.status.to_input()
        return _rval

    @staticmethod
    def from_input(obj) -> "UserAuditConfig | None":
        if not obj:
            return None
        _kind = obj.get(constants.Y_KIND)
        _api_version = obj.get(constants.Y_APIVERSION)
        _metadata = (
            ext_k8s_io_apimachinery_pkg_apis_meta_v1.ObjectMeta.from_input(obj.get(constants.Y_METADATA))
            if obj.get(constants.Y_METADATA, None)
            else ext_k8s_io_apimachinery_pkg_apis_meta_v1.ObjectMeta.from_name(obj.get(constants.Y_NAME))
        )
        _spec = UserAuditConfigSpec.from_input(obj.get(constants.Y_SPEC))
        _status = UserAuditConfigStatus.from_input(obj.get(constants.Y_STATUS))
        return UserAuditConfig(
            kind=_kind,
            api_version=_api_version,
            metadata=_metadata,
            spec=_spec,
            status=_status,
        )


class UserAuditConfigList:
    def __init__(
        self,
        items: list[UserAuditConfig],
        kind: str | None = None,
        api_version: str | None = None,
        metadata: ext_k8s_io_apimachinery_pkg_apis_meta_v1.ListMeta | None = None,
    ):
        self.kind = kind
        self.api_version = api_version
        self.metadata = metadata
        self.items = items

    def to_input(self):
        _rval = {}
        if self.kind is not None:
            _rval[constants.Y_KIND] = self.kind
        if self.api_version is not None:
            _rval[constants.Y_APIVERSION] = self.api_version
        if self.metadata is not None:
            _rval[constants.Y_METADATA] = self.metadata.to_input()
        _rval[constants.Y_ITEMS] = [x.to_input() for x in self.items]
        return _rval

    @staticmethod
    def from_input(obj) -> "UserAuditConfigList | None":
        if not obj:
            return None
        _kind = obj.get(constants.Y_KIND)
        _api_version = obj.get(constants.Y_APIVERSION)
        _metadata = ext_k8s_io_apimachinery_pkg_apis_meta_v1.ListMeta.from_input(obj.get(constants.Y_METADATA))
        _items = []
        if obj.get(constants.Y_ITEMS) is not None:
            for _e in obj.get(constants.Y_ITEMS):
                _items.append(UserAuditConfig.from_input(_e))
        return UserAuditConfigList(
            kind=_kind,
            api_version=_api_version,
            metadata=_metadata,
            items=_items,
        )
