apiVersion: apps/v1
kind: Deployment
metadata:
  name: eda-useraudit
  namespace: eda-system
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      eda.nokia.com/app: eda-useraudit
  template:
    metadata:
      name: useraudit
      namespace: eda-system
      labels:
        eda.nokia.com/app: eda-useraudit
        eda.nokia.com/app-group: control-plane
    spec:
      serviceAccountName: eda-useraudit
      terminationGracePeriodSeconds: 30
      securityContext:
        fsGroup: 65534
        fsGroupChangePolicy: OnRootMismatch
      containers:
        - name: useraudit-controller
          image: ghcr.io/kkayhan/edaapp_useraudit/useraudit-controller:v0.7.1
          imagePullPolicy: IfNotPresent
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          ports:
            - name: fileserver
              containerPort: 8080
              protocol: TCP
          startupProbe:
            httpGet:
              path: /healthz
              port: fileserver
            failureThreshold: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: fileserver
            periodSeconds: 30
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /healthz
              port: fileserver
            periodSeconds: 10
          volumeMounts:
            - name: log-data
              mountPath: /data/logs
          resources:
            limits:
              cpu: "200m" # app-set: ${controllerCpuLimit}
              memory: "128Mi" # app-set: ${controllerMemoryLimit}
            requests:
              cpu: "50m"
              memory: "64Mi"
      volumes:
        - name: log-data
          persistentVolumeClaim:
            claimName: useraudit-data
