//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogFileInfo) DeepCopyInto(out *LogFileInfo) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogFileInfo.
func (in *LogFileInfo) DeepCopy() *LogFileInfo {
	if in == nil {
		return nil
	}
	out := new(LogFileInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubsystemHealth) DeepCopyInto(out *SubsystemHealth) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubsystemHealth.
func (in *SubsystemHealth) DeepCopy() *SubsystemHealth {
	if in == nil {
		return nil
	}
	out := new(SubsystemHealth)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UserAuditConfig) DeepCopyInto(out *UserAuditConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UserAuditConfig.
func (in *UserAuditConfig) DeepCopy() *UserAuditConfig {
	if in == nil {
		return nil
	}
	out := new(UserAuditConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *UserAuditConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UserAuditConfigList) DeepCopyInto(out *UserAuditConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]UserAuditConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UserAuditConfigList.
func (in *UserAuditConfigList) DeepCopy() *UserAuditConfigList {
	if in == nil {
		return nil
	}
	out := new(UserAuditConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *UserAuditConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UserAuditConfigSpec) DeepCopyInto(out *UserAuditConfigSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UserAuditConfigSpec.
func (in *UserAuditConfigSpec) DeepCopy() *UserAuditConfigSpec {
	if in == nil {
		return nil
	}
	out := new(UserAuditConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UserAuditConfigStatus) DeepCopyInto(out *UserAuditConfigStatus) {
	*out = *in
	if in.LogFiles != nil {
		in, out := &in.LogFiles, &out.LogFiles
		*out = make([]LogFileInfo, len(*in))
		copy(*out, *in)
	}
	out.Subsystems = in.Subsystems
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UserAuditConfigStatus.
func (in *UserAuditConfigStatus) DeepCopy() *UserAuditConfigStatus {
	if in == nil {
		return nil
	}
	out := new(UserAuditConfigStatus)
	in.DeepCopyInto(out)
	return out
}
